### ISSUE TITLE
GDV formula error

### ISSUE THREAD

**Issue by nillkitty** [pellsson/nes_re#1]
When you converted your LUA script to psuedo-code,  you used `max()` but it really should be `min()` because you're awarding *up to 5* points.  I had implemented your logic exactly as described for [SKX](https://github.com/nillkitty/SKX) but noticed it was always 5 higher than it should have been. 

```GDV = (((has_page_of_space + has_page_of_time + 1 + (fairies/10) + saved_princess) * 2 + beaten_levels + solomon_seals) * 2 + hard_levels) / 8 + max(5, score/100000) + has_solomons_key + 47```

should be:

```GDV = (((has_page_of_space + has_page_of_time + 1 + (fairies/10) + saved_princess) * 2 + beaten_levels + solomon_seals) * 2 + hard_levels) / 8 + min(5, score/100000) + has_solomons_key + 47```

**Comment by pellsson** [comment]
Thank you so much for reporting it :)

I've updated accordingly.

I proceeded to translate the entire ROM to ca64 asm (I thiiink I finalized it...?) after I did the GDV thing. Also started reverse-engineering room descriptor format and things like that. Let me know if you are interested and I'll share it somehow :)

**Comment by nillkitty** [comment]
Funnily enough I never needed that.  I used an old level editor called SKEdit which inflates the ROM by switching the mapper to 066 and decompressing the levels into the format the game uses in-RAM.   I used that somewhat-easier format to import all the level data into my project.  I had started out by disassembling the game logic but after I realized there wasn't much I could do within the confines of the hardware besides minor tweaks, I started work on the rewrite..

**Comment by pellsson** [comment]
Ah fair enough :)

Let me know if you need any other logic from the original game; jump physics or whatever :) and good luck with the rewrite!

**Comment by nillkitty** [comment]
Here are some things I'm happy I was able to do outside the confines of the 6502 and PPU:

Translucent overlay with scrolling:
![image](https://user-images.githubusercontent.com/42795372/105178709-67829d80-5af6-11eb-8a0a-100c632d292f.png)
Complicated menus and file I/O:
![image](https://user-images.githubusercontent.com/42795372/105178858-926cf180-5af6-11eb-92c2-937f9fc758b2.png)
Transparent compositing
![image](https://user-images.githubusercontent.com/42795372/105178898-a153a400-5af6-11eb-8567-7c9d321f28b5.png)
Mouse UI control
![image](https://user-images.githubusercontent.com/42795372/105178951-b4ff0a80-5af6-11eb-80a0-f0dc1b37a56f.png)
Superforeground layer and pixel shader backgrounds
![image](https://user-images.githubusercontent.com/42795372/105179076-d6f88d00-5af6-11eb-9005-2cf1d1bfec9c.png)
input indirection
![image](https://user-images.githubusercontent.com/42795372/105179161-f68fb580-5af6-11eb-9d6d-001edf1760e5.png)
integrated editor:
![image](https://user-images.githubusercontent.com/42795372/105179274-1de68280-5af7-11eb-8ee3-4c1e3b70f51c.png)
large scale levels:
![image](https://user-images.githubusercontent.com/42795372/105179364-41a9c880-5af7-11eb-9410-20dd01313578.png) 
Fun stuff:
https://www.youtube.com/watch?v=dnbLJnLq4UU
https://www.youtube.com/watch?v=U1OKi5EFPLQ

There's a few things that you might be able to help with but I'll have to quantify exactly what they are first...  one that comes to mind is a nice pseudocode representation of the fairy AI.

**Comment by pellsson** [comment]
Wow! :D Look amazing :) Impressive work!

Yeah just let me know if I can help out. I have no private projects on the backburner currently and small RE-tasks for the NES are the prefect scope of what I have time for atm :)

**Comment by nillkitty** [comment]
- What's the best way to contact you besides this thread?
- Your help would be much appreciated;  already credited you for the GDV work
- Biggest two things right now are pseudocode (or even commented ASM) on 1) Fairy AI and 2) Dana's level collision 
- Mostly everything else I was able to get close to pixel-perfect just from observation (many of the enemies re-use the same velocities and routines it seems) and what isn't perfect probably won't be perfect (because the lack of lag frames means the enemies are going to perform faster on PC anyway without artificially emulating lag which is beyond the scope of how accurate I want to get -- notably Room 7 plays much different when the enemy AI isn't lagging) but I'm also happy to give you early access to the code and binaries so you can see what jumps out at you as broken/off.

**Comment by nillkitty** [comment]
Contact me;   nill@nillkitty.net;  twitter/telegram @nillkitty
